### ISSUE TITLE
Fail to open demo data

### ISSUE THREAD

**Issue by finetjul** [Kitware/paraview-glance#412] opened 2021-09-28 08:43 UTC
When trying to open `https://kitware.github.io/paraview-glance/app/` with the [T-handle dataset](https://user-images.githubusercontent.com/219044/135053694-cbaf589b-380d-4a72-b1c2-1e27b05f32a2.png) , it fails to load and the following errors are printed to the console:

![image](https://user-images.githubusercontent.com/219044/135053554-4d379450-29ae-4a6b-851e-9b93539d46de.png)

**Comment by jourdain** [comment] 2021-09-28 14:30
Duplicate of https://github.com/Kitware/paraview-glance/issues/410

**Comment by floryst** [comment] 2021-11-08 21:46
This should now be fixed in master and stable.

**Closed by floryst** 2021-11-08 21:46 UTC
